[package]
name = "text-to-fs2i"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
rig-fastembed = "0.2.0"
rig-core = "0.13.0"
tokio = { version = "1", features = ["full"] }
whatlang = "0.13"
lingua = "1.6"
stopwords = "0.1.1"
serde = "1.0.219"
chrono = "0.4.41"