[package]
name = "text-to-fs2i"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
rig-fastembed = "0.2.0"
anyhow = "1.0.98"
rig-core = "0.13.0"
tokio = { version = "1", features = ["full"] }